# Generated by Django 3.0.8 on 2020-07-03 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='(- 없이 입력)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='It is not a phone number format.', regex='[0-9]{9,11}')], verbose_name='대표전화')),
                ('name', models.CharField(max_length=255, verbose_name='학원명')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('address_zip', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='It is not a zip code format.', regex='[0-9]{5}')], verbose_name='우편번호')),
                ('address_state', models.CharField(max_length=30, verbose_name='광역시/도')),
                ('address_city', models.CharField(max_length=30, verbose_name='시/군/구')),
                ('address_district', models.CharField(max_length=30, verbose_name='읍/면/동')),
                ('address_street', models.CharField(max_length=30, verbose_name='도로명')),
                ('address_building', models.IntegerField(verbose_name='건물 번호')),
                ('address_detail', models.CharField(max_length=255, verbose_name='상세 주소')),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('국어', '국어'), ('수학', '수학'), ('영어', '영어'), ('사회', '사회'), ('과학', '과학'), ('제2외국어', '제2외국어'), ('정보', '정보'), ('미술', '미술'), ('음악', '음악'), ('체육', '체육'), ('그 외', '그 외')], max_length=20, verbose_name='과목')),
                ('target_ages', multiselectfield.db.fields.MultiSelectField(choices=[('미취학', '미취학'), ('초등', '초등'), ('중등', '중등'), ('고등', '고등'), ('재수생', '재수생'), ('성인', '성인')], max_length=20, verbose_name='대상층')),
                ('description', models.TextField(blank=True, verbose_name='학원 소개')),
            ],
            options={
                'verbose_name': '학원',
                'verbose_name_plural': '학원',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='별점')),
                ('text', models.TextField(verbose_name='내용')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academy.Academy', verbose_name='대상 학원')),
            ],
            options={
                'verbose_name': '학원 리뷰',
                'verbose_name_plural': '학원 리뷰',
            },
        ),
        migrations.CreateModel(
            name='StudentInAcademy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, verbose_name='학생 고유번호')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_academy', to='academy.Academy', verbose_name='학원')),
            ],
            options={
                'verbose_name': '학원당 학생 계정 정보',
                'verbose_name_plural': '학원당 학생 계정 정보',
                'unique_together': {('academy', 'student_number')},
            },
        ),
    ]
