# Generated by Django 3.0.8 on 2020-07-03 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('academy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_student', models.BooleanField(default=True, verbose_name='학생 계정')),
                ('is_parent', models.BooleanField(default=False, verbose_name='학부모 계정')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='선생님 계정')),
                ('phone', models.CharField(help_text='(- 없이 입력)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='It is not a phone number format.', regex='[0-9]{9,11}')], verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 계정')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 계정')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 계정')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 계정')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '계정',
                'verbose_name_plural': '계정',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL, verbose_name='계정')),
            ],
            options={
                'verbose_name': '학부모 계정 정보',
                'verbose_name_plural': '학부모 계정 정보',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='학원 관리자 계정')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academy.Academy', verbose_name='소속 학원')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='계정')),
            ],
            options={
                'verbose_name': '선생님 계정 정보',
                'verbose_name_plural': '선생님 계정 정보',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='user.Parent', verbose_name='학부모')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='계정')),
            ],
            options={
                'verbose_name': '학생 계정 정보',
                'verbose_name_plural': '학생 계정 정보',
            },
        ),
    ]
